<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="41" started-at="2020-08-12T15:47:37 EEST" finished-at="2020-08-12T15:47:37 EEST">
    <groups>
    </groups>
    <test name="Test" duration-ms="41" started-at="2020-08-12T15:47:37 EEST" finished-at="2020-08-12T15:47:37 EEST">
      <class name="Section14Subsection117Maven.AppiumFramework.ecommerce_tc_4">
        <test-method status="FAIL" signature="totalValidadion()[pri:0, instance:Section14Subsection117Maven.AppiumFramework.ecommerce_tc_4@63440df3]" name="totalValidadion" duration-ms="7" started-at="2020-08-12T15:47:37 EEST" finished-at="2020-08-12T15:47:37 EEST">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[null\src\main\java\Section14Subsection117Maven\AppiumFramework\global.properties (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: null\src\main\java\Section14Subsection117Maven\AppiumFramework\global.properties (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at Section14Subsection117Maven.AppiumFramework.base.Capabilities(base.java:24)
at Section14Subsection117Maven.AppiumFramework.ecommerce_tc_4.totalValidadion(ecommerce_tc_4.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalValidadion -->
      </class> <!-- Section14Subsection117Maven.AppiumFramework.ecommerce_tc_4 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
